const Heroes = [
    {
        id: 'Axe',
        name: 'Axe',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/2/23/Axe_icon.png',
        desc: 'Mogul Khan, the Axe, is a melee strength hero, infamous for creating chaos in battle and thriving off of it. Axe is commonly played as an initiator, as his potent disables can disrupt the enemy\'s formation and give his team openings in fights.',
        talents: [
            ['+100 Battle Hunger DPS', '25', '+800 Berserker\'s Call'],
            ['+20 Health Regen', '20', '+180 Culling Blade Kill Threshold'],
            ['+Attacking Proc Counter Helix', '15', '+5 Mana Regen'],
            ['+20 Movement Speed', '10', '+25 Attack Speed'],
        ],
        abilities: ['beserkersCall', 'battleHunger', 'counterHelix', 'cullingBlade', 'talentTree'],
        shards: ['pathfinder_axe_special_berseker_call_battle_hunger',
            'pathfinder_axe_special_berseker_call_health',
            'pathfinder_axe_special_berseker_call_allies',
            'pathfinder_axe_special_battle_hunger_lifesteal',
            'pathfinder_axe_special_battle_hunger_culling_cdr',
            'pathfinder_axe_special_battle_hunger_refresh',
            'pathfinder_axe_special_counter_helix_allies',
            'pathfinder_axe_special_counter_helix_fury',
            'pathfinder_axe_special_counter_helix_reduce_damage',
            'pathfinder_axe_special_culling_blade_heal',
            'pathfinder_axe_special_berseker_call_blink',
            'pathfinder_axe_special_culling_blade_delay',
            'pathfinder_axe_special_culling_blade_leap']
    },
    {
        id: 'LegionCommander',
        name: 'Legion Commander',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a2/Legion_Commander_icon.png',
        desc: 'Tresdin, the Legion Commander, is a melee strength hero fitting the role of carry. A highly mobile and somewhat tanky hero, her skillset and gameplay revolve mainly around killing off targets and especially backliners and supports, with her ultimate, Duel.' +
            'Each successful Duel grants Tresdin permanent bonus damage. Though she is extremely skilled in "fair" one-on-one fights, Tresdin suffers when outnumbered and must choose her engagements carefully.',
        talents: [
            ['+65 Press The Attack HP Regen', '25', '+350 Overwhelming Odds Base Damage'],
            ['+7% Moment Proc Chance', '20', '+30 Movement Speed'],
            ['+5s Overwhelming Odds Movespeed Duration', '15', '+25 Attack Speed'],
            ['+1.5 Mana Regen', '10', '+7 Strength'],
        ],
        abilities: ['overwhelmingOdds', 'pressTheAttack', 'momentOfCourage', 'duel', 'talentTree'],
        shards: ['pathfinder_special_lc_global_arrows_dummy',
            'pathfinder_special_lc_duel_arrows',
            'pathfinder_special_lc_duel_legion',
            'pathfinder_special_lc_duel_purge',
            'pathfinder_special_lc_arrows_meteor',
            'pathfinder_special_lc_arrows_reset',
            'pathfinder_special_lc_moment_aoe',
            'pathfinder_special_lc_press_blademail',
            'pathfinder_special_lc_press_bkb']
    },
    {
        id: 'Magnus',
        name: 'Magnus',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/b/ba/Magnus_icon.png',
        desc: 'Magnus, the Magnoceros, is a monstrous melee strength hero who is usually played as a ganker, initiator, or semi-carry. His ability to battle multiple heroes at once gives him an excellent presence in team fights.' +
            'In addition to his teamfight presence, he can buff allies or himself with bonus damage and cleave, capitalizing on his ability to group up multiple enemies.',
        talents: [
            ['+1s Reverse Polarity Stun Duration', '25', '+10% Empower Damage/Cleave'],
            ['+425 Skewer Range', '20', '+350 Health'],
            ['-5s Skewer Cooldown', '15', '+8 Strength'],
            ['+200 Mana', '10', '+20 Damage'],
        ],
        abilities: ['shockwave', 'empower', 'skewer', 'reversePolarity', 'talentTree'],
        shards: ['aghsfort_special_magnataur_shockwave_multishot',
            'aghsfort_special_magnataur_shockwave_damage_reduction',
            'aghsfort_special_magnataur_shockwave_boomerang',
            'aghsfort_special_magnataur_empower_all_allies',
            'aghsfort_special_magnataur_empower_lifesteal',
            'aghsfort_special_magnataur_empower_shockwave_on_attack',
            'aghsfort_special_magnataur_skewer_bonus_strength',
            'aghsfort_special_magnataur_skewer_heal',
            'aghsfort_special_magnataur_skewer_shockwave',
            'aghsfort_special_magnataur_reverse_polarity_polarity_dummy',
            'aghsfort_special_magnataur_reverse_polarity_allies_crit',
            'aghsfort_special_magnataur_reverse_polarity_steroid']
    },
    {
        id: 'Mars',
        name: 'Mars',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/9/9d/Mars_icon.png',
        desc: 'Mars, the First Son of Heaven, is an aggressive melee strength hero who controls the battlefield with numerous knockbacks and impassable terrain.' +
            'Equipped with a large shield, his Bulwark passively blocks attacks from the front and sides, making him a very durable fighter in most situations.',
        talents: [
            ['Arena of Blood Grants Team +120 HP Regen', '25', 'God\'s Rebuke +65% Crit'],
            ['+0.8s Spear of Mars Stun', '20', '+160 Spear Of Mars Damage'],
            ['+6 Armor', '15', '-4s God\'s Rebuke Cooldown'],
            ['+175 Health', '10', '+15 Damage'],
        ],
        abilities: ['spearOfMars', 'godsRebuke', 'bulwark', 'arenaOfBlood', 'talentTree'],
        shards: ['aghsfort_special_mars_spear_multiskewer',
            'aghsfort_special_mars_spear_impale_explosion',
            'aghsfort_special_mars_spear_burning_trail',
            'aghsfort_special_mars_gods_rebuke_full_circle',
            'aghsfort_special_mars_gods_rebuke_stun',
            'aghsfort_special_mars_gods_rebuke_strength_buff',
            'aghsfort_special_mars_bulwark_counter_rebuke',
            'aghsfort_special_mars_bulwark_spears',
            'aghsfort_special_mars_bulwark_soldiers',
            'aghsfort_special_mars_arena_of_blood_global',
            'aghsfort_special_mars_arena_of_blood_attack_buff',
            'aghsfort_special_mars_arena_of_blood_outside_perimeter']
    },
    {
        id: 'Omniknight',
        name: 'Omniknight',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/e/e2/Omniknight_icon.png',
        desc: 'Purist Thunderwrath, the Omniknight, is a melee strength hero who is renowned for his ability to protect his allies, preventing the enemy from easily killing them.' +
            'A holy and courageous hero, Purist Thunderwrath is an adept support whose powerful spells give his team strong survivability.',
        talents: [
            ['-3s Heavenly Grace Cooldown', '25', '+160 Purification Damage/Heal'],
            ['+3 Mana Regen', '20', '-15% Degen Aura'],
            ['+30 Movement Speed', '15', '+6 Armor'],
            ['+40 Base Damage', '10', '+250 Mana'],
        ],
        abilities: ['purification', 'heavenlyGrace', 'degenAura', 'guardianAngel', 'talentTree'],
        shards: ['aghsfort_special_omniknight_purification_cast_radius',
            'aghsfort_special_omniknight_purification_charges',
            'aghsfort_special_omniknight_purification_multicast',
            'aghsfort_special_omniknight_repel_procs_purification',
            'aghsfort_special_omniknight_repel_outgoing_damage',
            'aghsfort_special_omniknight_repel_damage_instance_refraction',
            'aghsfort_special_omniknight_repel_knockback_on_cast',
            'aghsfort_special_omniknight_degen_aura_toggle',
            'aghsfort_special_omniknight_degen_aura_damage',
            'aghsfort_special_omniknight_degen_aura_restoration',
            'aghsfort_special_omniknight_guardian_angel_purification',
            'aghsfort_special_omniknight_guardian_angel_immune_flight',
            'aghsfort_special_omniknight_guardian_angel_single_target_dummy']
    },
    {
        id: 'Snapfire',
        name: 'Snapfire',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/7/7a/Snapfire_icon.png',
        desc: 'Beatrix Snapfire, or simply Snapfire, is a ranged strength hero armed with a wide array of firepower, riding into battle on her dragon toad Mortimer.',
        talents: [
            ['+6 Mortimer Kisses Launched', '25', '+90 Damage'],
            ['+20% Mortimer Kisses Movement Slow', '20', 'Lil\' Shredder Uses Your Attack Damage'],
            ['+60 Scatterblast Damage', '15', 'Firesnap Cookie Restores 200 Health'],
            ['+20 Movement Speed', '10', '+200 Health'],
        ],
        abilities: ['scatterblast', 'firesnapCookie', 'lilShredder', 'mortimerKisses', 'talentTree'],
        shards: ['aghsfort_special_snapfire_scatterblast_double_barrel',
            'aghsfort_special_snapfire_scatterblast_knockback',
            'aghsfort_special_snapfire_scatterblast_barrage',
            'aghsfort_special_snapfire_firesnap_cookie_multicookie',
            'aghsfort_special_snapfire_firesnap_cookie_enemytarget',
            'aghsfort_special_snapfire_firesnap_cookie_allied_buff',
            'aghsfort_special_snapfire_lil_shredder_explosives',
            'aghsfort_special_snapfire_lil_shredder_ally_cast',
            'aghsfort_special_snapfire_lil_shredder_bouncing_bullets',
            'aghsfort_special_snapfire_mortimer_kisses_fragmentation',
            'aghsfort_special_snapfire_mortimer_kisses_autoattack',
            'aghsfort_special_snapfire_mortimer_kisses_incoming_damage_reduction']
    },
    {
        id: 'Tidehunter',
        name: 'Tidehunter',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d5/Tidehunter_icon.png',
        desc: 'Leviathan, the Tidehunter, is a melee strength hero who is formidable due to his uncommonly tough hide and his ocean spells that sweep enemies upward.' +
            'He can be played as a support or as an offlane hero whose greatest strengths lie in being able to take heavy amounts of damage in the early game and the disabling powers of his spells.',
        talents: [
            ['+200 Damage', '25', '20% Coooldown Reduction'],
            ['+4 Gush Armour Reduction', '20', '+30 Shell Damage Block'],
            ['+15% Anchor Smash Attack Damage Reduction', '15', '+5 Mana Regen'],
            ['+90 Gush Damage', '10', '+15 Movement Speed'],
        ],
        abilities: ['gush', 'krakenShell', 'anchorSmash', 'ravage', 'talentTree'],
        shards: ['tidehunter_gush_pf_miss',
            'tidehunter_gush_pf_ravage',
            'tidehunter_gush_pf_bounce',
            'tidehunter_anchor_smash_pf_whack',
            'tidehunter_anchor_smash_pf_karate',
            'tidehunter_anchor_smash_pf_allies',
            'tidehunter_kraken_shell_pf_heal',
            'tidehunter_kraken_shell_pf_ravage_cdr',
            'tidehunter_kraken_shell_pf_gush',
            'tidehunter_ravage_pf_puddle',
            'tidehunter_pf_crunch']
    },
    {
        id: 'Tusk',
        name: 'Tusk',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/c/ce/Tusk_icon.png',
        desc: 'Ymir, the Tusk, is a melee strength hero whose array of icy disables makes him a very strong team initiator and ganker.' +
            'He has a damage nuke and a disable in Ice Shards, which lets him precisely place a barrier in an enemy\'s path, inhibiting their movement and blocking off their escape path.',
        talents: [
            ['+40 Attack Speed', '25', '+12% Chance Walrus Punch'],
            ['+80% Walrus Punch Crit', '20', '+30 Movement Speed'],
            ['+120 Snowball Damage', '15', '+325 Health'],
            ['+0.4s Walrus Punch Stun Duration', '10', '+8 Health Regen'],
        ],
        abilities: ['iceShards', 'snowball', 'tagTeam', 'walrusPunch', 'talentTree'],
        shards: ['aghsfort_special_tusk_ice_shards_explode',
            'aghsfort_special_tusk_ice_shards_stun',
            'aghsfort_special_tusk_ice_shards_secondary',
            'aghsfort_special_tusk_snowball_heal',
            'aghsfort_special_tusk_snowball_end_damage',
            'aghsfort_special_tusk_snowball_global',
            'aghsfort_special_tusk_tag_team_lifesteal',
            'aghsfort_special_tusk_tag_team_toggle',
            'aghsfort_special_tusk_tag_team_global',
            'aghsfort_special_tusk_walrus_punch_reset',
            'aghsfort_special_tusk_walrus_punch_land_damage',
            'aghsfort_special_tusk_walrus_punch_wallop',
            'tusk_frozen_sigil_pf']
    },
    {
        id: 'Hoodwink',
        name: 'Hoodwink',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c9/Hoodwink_icon.png',
        desc: 'Hoodwink is a tricky ranged agility hero who runs wild through the trees of Mistwoods. Firing acorns from her arbalest, she creates new forests through which to Scurry.' +
            'For her foes, the woods are a dangerous place, full of  Bushwhack traps and vantage points for the  Sharpshooter to aim the ultimate crossbow shot. This crafty critter should never be underestimated.',
        talents: [
            ['+40% Magic Resistance', '25', '+9000 Sharpshooter Range'],
            ['-3 Armor Corruption', '20', '+4 Acorn Shot Bounces'],
            ['+14 Agility', '15', 'Sharpshooter Grants Invisibility'],
            ['+30 Movement Speed', '10', '+200 Health'],
        ],
        abilities: ['acornShot', 'bushwhack', 'scurry', 'sharpshooter', 'talentTree'],
        shards: ['pathfinder_bushwhack_multi_attack',
            'pathfinder_bushwhack_ground',
            'pathfinder_acorn_shot_stun',
            'pathfinder_scurry_canadian',
            'pathfinder_acorn_shot_tree',
            'pathfinder_acorn_shot_attack',
            'pathfinder_sharpshooter_pierce',
            'pathfinder_sharpshooter_reset',
            'pathfinder_scurry_leap',
            'pathfinder_scurry_allies',
            'pathfinder_bushwhack_scurry']
    },
    {
        id: 'Juggernaut',
        name: 'Juggernaut',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/0/03/Juggernaut_icon.png',
        desc: 'Yurnero, the Juggernaut, is a melee agility hero whose abilities allow him to sprint into battle and recklessly devastate enemies in an impenetrable flurry of blades. \
        \nHis abilities grant invulnerability and spell immunity, turning him into an unstoppable force on a hairpin.',
        talents: [
            ['+1s Omnislash Duration', '25', '+475 health'],
            ['+160 Blade Fury DPS', '20', '+8 Armor'],
            ['+20 Attack Speed', '15', '-20 Healing Ward cooldown'],
            ['+20 Movement Speed', '10', '+5 All Stats'],
        ],
        abilities: ['bladeFury', 'healingWard', 'bladeDance', 'omnislash', 'talentTree'],
        shards: ['pathfinder_special_juggernaut_blade_dance_reduce_omnislash_cooldown',
            'pathfinder_special_juggernaut_wind_breathing_dummy',
            'pathfinder_special_juggernaut_blade_fury_flying',
            'pathfinder_special_juggernaut_blade_fury_ward',
            'pathfinder_special_juggernaut_blade_fury_strength',
            'pathfinder_special_juggernaut_healing_ward_earthshock',
            'pathfinder_special_juggernaut_healing_ward_creep',
            'pathfinder_special_juggernaut_healing_ward_radiance',
            'pathfinder_special_juggernaut_healing_ward_allies',
            'pathfinder_special_juggernaut_blade_dance_illusion']
    },
    {
        id: 'PhantomAssassin',
        name: 'Phantom Assassin',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/8/8e/Phantom_Assassin_icon.png',
        desc: 'Mortred, the Phantom Assassin, is a melee agility hero fitting the role of hard carry. Mortred is best-known, and infamous for, her ability to inflict staggering damage with single strikes.' +
            'Her abilities synergize supremely well with each other, rendering her an extremely formidable foe once she has acquired the items she requires.',
        talents: [
            ['+100% Coup De Grace Crit Damage', '25', '+40% Blur Evasion'],
            ['Global Phantom Strike Range', '20', '-3 Armor Corruption'],
            ['+3s Phantom Strike Buff Duration', '15', '12% Lifesteal'],
            ['-400% Stifling Dagger Movement Slow', '10', '+175 Health'],
        ],
        abilities: ['stiflingDagger', 'phantomStrike', 'blur', 'coupDeGrace', 'talentTree'],
        shards: ['pathfinder_special_pa_dagger_bouncing',
            'pathfinder_special_pa_blur_cdr',
            'pathfinder_special_pa_blink_illusion',
            'pathfinder_special_pa_blink_aoe',
            'pathfinder_special_pa_blur_aoe',
            'pathfinder_special_pa_blur_block',
            'pathfinder_special_pa_crit_fear',
            'pathfinder_special_pa_crit_lifesteal',
            'phantom_assassin_dagger_global_dummy',
            'pathfinder_special_pa_crit_dagger',
            'pathfinder_special_pa_blur_regen']
    },
    {
        id: 'ShadowFiend',
        name: 'Shadow Fiend',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/3/36/Shadow_Fiend_icon.png',
        desc: 'Nevermore, the Shadow Fiend, is a ranged agility hero possessing abilities that inflict superb burst damage from varying distances. Whether near or far, Shadow Fiend is able to release incredible' +
            'offensive power, both physical and magical. Shadow Fiend\'s true power comes from the souls he takes, making him more dangerous every time he kills.',
        talents: [
            ['30% Cooldown Reduction', '25', 'Global Dark Lord Aura'],
            ['+150 Shadowraze Damage', '20', '+3 Damage per Soul'],
            ['+30 Movement Speed', '15', '+100 Attack Range'],
            ['+15 Attack Speed', '10', '+6% Spell Amplification'],
        ],
        abilities: ['shadowraze', 'necromastery', 'presenceOfTheDarkLord', 'requiemOfSouls', 'talentTree'],
        shards: ['pathfinder_nevermore_special_necromastery_revenant',
            'pathfinder_nevermore_special_raze_multi',
            'pathfinder_nevermore_special_dark_lord_raze',
            'pathfinder_nevermore_special_requiem_soul_projectile',
            'pathfinder_nevermore_special_requiem_sleep',
            'pathfinder_nevermore_special_dark_lord_split_attack',
            'pathfinder_nevermore_special_necromastery_attack_soul',
            'pathfinder_nevermore_special_requiem_attack',
            'pathfinder_nevermore_special_dark_lord_friendly',
            'pathfinder_nevermore_special_necromastery_lifesteal']
    },
    {
        id: 'Slark',
        name: 'Slark',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/a/aa/Slark_icon.png',
        desc: 'Slark, the Nightcrawler, is a melee agility hero that utilizes his abilities to spring onto enemy heroes and slip out unhindered. He is a very mobile ganker, but remains attribute-wise below most other carries unless he is able to steal away attributes with his abilities.' +
            'Once he does, though, only a few heroes can hope to be as fearsome as the Nightcrawler - extremely mobile to the point of ever-presence, his strikes only hitting harder and faster.',
        talents: [
            ['+475 Health', '25', '+1s Shadow Dance Duration'],
            ['+0.8s Pounce Leash', '20', '+120 Dark Pact Damage'],
            ['15% Lifesteal', '15', '+20 Attack Speed'],
            ['20 Movement Speed', '10', '+5 All Stats'],
        ],
        abilities: ['darkPact', 'pounce', 'essenceShift', 'shadowDance', 'talentTree'],
        shards: ['aghsfort_special_slark_dark_pact_essence_shift',
            'aghsfort_special_slark_dark_pact_push_stun',
            'aghsfort_special_slark_dark_pact_unit_target',
            'aghsfort_special_slark_pounce_attack_all',
            'aghsfort_special_slark_pounce_projectiles',
            'aghsfort_special_slark_pounce_leashed_bonus',
            'aghsfort_special_slark_essence_shift_aoe_attack',
            'aghsfort_special_slark_essence_shift_leash_chance',
            'aghsfort_special_slark_essence_shift_allied_buff',
            'aghsfort_special_slark_shadow_dance_dark_pact_pulses',
            'aghsfort_special_slark_shadow_dance_essence_shift_bonus',
            'aghsfort_special_slark_shadow_dance_leash']
    },
    {
        id: 'Sniper',
        name: 'Sniper',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/5/51/Sniper_icon.png',
        desc: 'Kardel Sharpeye, the Sniper, is a ranged agility hero who excels at dealing moderate to heavy damage from an incredible range. With no escape mechanism, poor mobility, and a low health pool, Sniper is' +
            'exceptionally frail at all stages of the game and vulnerable to enemies who confront him head-on. However, his abilities provide him both the means to keep his distance and systematically destroy his enemies from afar.',
        talents: [
            ['+5 Shrapnel Charges', '25', '+100 Attack Range'],
            ['+24 Shrapnel DPS', '20', '+28 Knockback Distance Headshot'],
            ['-14% Shrapnel Slow', '15', '+30 Attack Speed'],
            ['+15 Damage', '10', '15% Cooldown Reduction'],
        ],
        abilities: ['shrapnel', 'headshot', 'takeAim', 'assassinate', 'talentTree'],
        shards: ['aghsfort_special_sniper_shrapnel_bombs',
            'aghsfort_special_sniper_shrapnel_attack_speed',
            'aghsfort_special_sniper_shrapnel_miss_chance',
            'aghsfort_special_sniper_shrapnel_move_speed',
            'aghsfort_special_sniper_headshot_crits',
            'aghsfort_special_sniper_headshot_stuns',
            'aghsfort_special_sniper_take_aim_self_purge',
            'aghsfort_special_sniper_take_aim_hop_backwards',
            'aghsfort_special_sniper_take_aim_armor_reduction',
            'aghsfort_special_sniper_take_aim_rapid_fire',
            'aghsfort_special_sniper_assassinate_buckshot',
            'aghsfort_special_sniper_assassinate_original_scepter',
            'aghsfort_special_sniper_assassinate_killshot']
    },
    {
        id: 'TemplarAssassin',
        name: 'Templar Assassin',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/9/9c/Templar_Assassin_icon.png',
        desc: 'Lanaya, the Templar Assassin, is a very short-ranged agility hero capable of dealing huge bursts of physical damage to swathes of enemies with expert positioning and timing. Unlike most physical damage dealers, Lanaya' +
            'reaches her damage potential quite early and then scales up from that point with carry items, letting her gank with impunity throughout the mid-game, and her short attack range increases from being comparable to that of a melee hero to a' +
            'ranged hero with short reach as she levels Psi Blades.',
        talents: [
            ['+6 Refraction Instances', '25', '1s Meld Hit Bash'],
            ['-3 Meld Armor Reduction', '20', 'Meld Dispels'],
            ['+160 Psionic Trap Damage', '15', '15% Evasion'],
            ['+20 Movement Speed', '10', '+15 Attack Speed'],
        ],
        abilities: ['refraction', 'meld', 'psiBlades', 'psionicTrap', 'talentTree'],
        shards: ['aghsfort_special_templar_assassin_refraction_kill_refresh',
            'aghsfort_special_templar_assassin_refraction_detonate_trap',
            'aghsfort_special_templar_assassin_refraction_allies',
            'aghsfort_special_templar_assassin_meld_attack_on_activation',
            'aghsfort_special_templar_assassin_meld_teleport',
            'aghsfort_special_templar_assassin_meld_refraction_on_kill',
            'aghsfort_special_templar_assassin_psi_blades_splash',
            'aghsfort_special_templar_assassin_psi_blades_trap',
            'aghsfort_special_templar_assassin_psionic_trap_multipulse',
            'aghsfort_special_templar_assassin_psionic_trap_damage_heals',
            'aghsfort_special_templar_assassin_psionic_trap_area_attack']
    },
    {
        id: 'Ursa',
        name: 'Ursa',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/4/40/Ursa_icon.png',
        desc: 'Ulfsaar, the Ursa Warrior (or simply Ursa), is a melee agility hero whose abilities\' main focus is the increase of attack damage, allowing for some of the most impressive sustained damage in the entire game.' |
            'He specializes in increasing damage against one target. His abilities allow him to attack with almost maximum speed and gain bonus damage with each consecutive hit on a single target.',
        talents: [
            ['+3 Overpower Attacks', '25', '+480 AoE Earthshock'],
            ['+12 Fury Swipes Damage', '20', '+1.2s Enrage Duration'],
            ['+350 Health', '15', '+12 Agility'],
            ['+1.5 Mana Regen', '10', '+20 Damage'],
        ],
        abilities: ['earthshock', 'overpower', 'furySwipes', 'Enrage', 'talentTree'],
        shards: ['aghsfort_special_ursa_earthshock_invis',
            'aghsfort_special_ursa_earthshock_knockback',
            'aghsfort_special_ursa_earthshock_apply_fury_swipes',
            'aghsfort_special_ursa_earthshock_overpower_stack',
            'aghsfort_special_ursa_overpower_crit',
            'aghsfort_special_ursa_overpower_evasion',
            'aghsfort_special_ursa_overpower_cleave',
            'aghsfort_special_ursa_fury_swipes_armor_reduction',
            'aghsfort_special_ursa_fury_swipes_lifesteal',
            'aghsfort_special_ursa_fury_swipes_ursa_minor',
            'aghsfort_special_ursa_enrage_allies',
            'aghsfort_special_ursa_enrage_fear',
            'aghsfort_special_ursa_enrage_attack_speed',
            'aghsfort_special_ursa_enrage_earthshock']
    },
    {
        id: 'Venomancer',
        name: 'Venomancer',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/2/25/Venomancer_icon.png',
        desc: 'Lesale Deathbringer, the Venomancer, is a ranged agility hero who is focused on dealing damage over time and slowing enemies down. While unassuming due to his mediocre stats and low attack range,' +
            'he can inflict surprising amounts of gradual damage with his poisonous abilities if left alone.',
        talents: [
            ['20% Cooldown Reduction', '25', '+20% Spell Amplification'],
            ['Plague Ward gains True Strike', '20', 'Plague Ward gains Split Shot'],
            ['+70 Attack Speed', '15', '+20 Plague Ward Duration'],
            ['+200 Health', '10', '+3 Mana Regen'],
        ],
        abilities: ['venomousGale', 'poisonSting', 'plagueWard', 'poisonNova', 'talentTree'],
        shards: ['pathfinder_special_venomancer_gale_bkb',
            'pathfinder_special_venomancer_ward_global_attack',
            'pathfinder_special_venomancer_ward_lifesteal',
            'pathfinder_special_venomancer_ward_corpse',
            'pathfinder_special_venomancer_ward_nova',
            'pathfinder_special_venomancer_gale_attack',
            'pathfinder_special_venomancer_banana_bomb',
            'pathfinder_special_venomancer_bigass_ward_dummy']
    },
    {
        id: 'Viper',
        name: 'Viper',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5f/Viper_icon.png',
        desc: 'Viper, the Netherdrake, is a ranged agility hero who functions as an excellent nuker, ganker and carry due to his assortment of low-cooldown spells and debilitating attacks. His modus operandi is to whittle away his opponents\'' +
            'vitality over long stretches of time while they fail to inflict fatal damage. To that end Viper wields magic-based abilities focused on inhibiting speed and defenses.',
        talents: [
            ['+30 Movement speed', '25', '+400 Health'],
            ['+70 Damage', '20', '+80 Viper Strike DPS'],
            ['+5 Corrosive Skin Stats', '15', '+100 Attack Range'],
            ['6% Spell Lifesteal', '10', '+20 Attack Speed'],
        ],
        abilities: ['poisonAttack', 'nethertoxin', 'corrosiveSkin', 'viperStrike', 'talentTree'],
        shards: ['aghsfort_special_viper_poison_snap',
            'aghsfort_special_viper_poison_attack_explode',
            'aghsfort_special_viper_poison_attack_spread',
            'aghsfort_special_viper_nethertoxin_charges',
            'aghsfort_special_viper_nethertoxin_lifesteal',
            'aghsfort_special_viper_nethertoxin_persist',
            'aghsfort_special_viper_corrosive_skin_speed_steal',
            'aghsfort_special_viper_corrosive_skin_flying',
            'aghsfort_special_viper_corrosive_skin_aura',
            'aghsfort_special_viper_viper_strike_allies',
            'aghsfort_special_viper_chain_viper_strike',
            'aghsfort_special_viper_periodic_strike']
    },
    {
        id: 'Weaver',
        name: 'Weaver',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/0/09/Weaver_icon.png',
        desc: 'Yurnero, the Juggernaut, is a melee agility hero whose abilities allow him to sprint into battle and recklessly devastate enemies in an impenetrable flurry of blades. \
        \nHis abilities grant invulnerability and spell immunity, turning him into an unstoppable force on a hairpin.',
        talents: [
            ['+1 Germinate Attack', '25', '+475 health'],
            ['+4 Swarm Attacks to Kill', '20', '+0.4 Swarm Armor Reduction'],
            ['+11 Strength', '15', '-3 Armor Corruption'],
            ['+6 Agility', '10', '+60 Shukuchi Damage'],
        ],
        abilities: ['theSwarm', 'shukuchi', 'geminateAttack', 'timeLapse', 'talentTree'],
        shards: ['aghsfort_special_weaver_swarm_allies',
            'aghsfort_special_weaver_swarm_explosion',
            'aghsfort_special_weaver_swarm_damage_transfer',
            'aghsfort_special_weaver_shukuchi_trail',
            'aghsfort_special_weaver_shukuchi_heal',
            'aghsfort_special_weaver_shukuchi_attack_on_completion',
            'aghsfort_special_weaver_shukuchi_swarm',
            'aghsfort_special_weaver_geminate_attack_splitshot',
            'aghsfort_special_weaver_geminate_attack_applies_swarm',
            'aghsfort_special_weaver_geminate_attack_lifesteal',
            'aghsfort_special_weaver_time_lapse_allies',
            'aghsfort_special_weaver_time_lapse_restoration',
            'aghsfort_special_weaver_time_lapse_explosion']
    },
    {
        id: 'Disruptor',
        name: 'Disruptor',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/9/97/Disruptor_icon.png',
        desc: 'Disruptor, the Stormcrafter, is a ranged intelligence hero who requires good positioning to use his abilities effectively. His signature ability is Kinetic Field, a pseudo-disable that traps enemies within a small area for a long duration.' +
            'Combined with his Static Storm, Disruptor can act as the initiator for a teamfight, or supplement his teammates\' initiation very well.',
        talents: [
            ['+3s Kinetic Field Duration', '25', '-8s Glimpse Cooldown'],
            ['+3 Thunder Strike Hits', '20', '+20 Intelligence'],
            ['-3s Kinetic Field Cooldown', '15', '+125 Cast Range'],
            ['+30 Thunder Strike Damage', '10', '+20% Magic Resistance'],
        ],
        abilities: ['thunderStrike', 'glimpse', 'kineticField', 'staticStorm', 'talentTree'],
        shards: ['aghsfort_special_disruptor_thunder_strike_interval_upgrade',
            'aghsfort_special_disruptor_thunder_strike_mana_restore',
            'aghsfort_special_disruptor_thunder_strike_crit_chance',
            'aghsfort_special_disruptor_thunder_strike_on_attack',
            'aghsfort_special_disruptor_glimpse_hit_on_arrival',
            'aghsfort_special_disruptor_glimpse_travel_damage',
            'aghsfort_special_disruptor_kinetic_field_damage',
            'aghsfort_special_disruptor_kinetic_field_allied_heal',
            'aghsfort_special_disruptor_kinetic_field_allied_attack_buff',
            'aghsfort_special_disruptor_kinetic_field_double_ring',
            'aghsfort_special_disruptor_static_storm_kinetic_field_on_cast',
            'aghsfort_special_disruptor_static_storm_crits_on_attacks',
            'aghsfort_special_disruptor_static_storm_damage_reduction']
    },
    {
        id: 'Jakiro',
        name: 'Jakiro',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/2/2f/Jakiro_icon.png',
        desc: 'Jakiro, the Twin Head Dragon, is a ranged intelligence hero who utilizes the powers of ice and fire with powerful linear area spells. He can freeze enemies in place with Ice Path, or slow them down with Dual Breath.' +
            'He is capable of dealing heavy damage throughout the game by locking enemies inside his Macropyre, and provides great pushing power with Liquid Fire.',
        talents: [
            ['+5 Ice Path Lifetime', '25', '+2000 Macropyre Length'],
            ['+325 Dual Breath Travel Distance', '20', '+50 Liquid Fire Attack Slow'],
            ['+25 Dual Breath Burn Damage', '15', '10% Cooldown Reduction'],
            ['+6% Spell Amplification', '10', '+325 Attack Range'],
        ],
        abilities: ['dualBreath', 'icePath', 'liquidFire', 'macropyre', 'talentTree'],
        shards: ['pathfinder_jakiro_duel_breath_ice_blob',
            'pathfinder_jakiro_dual_breath_fart',
            'pathfinder_jakiro_duel_breath_liquid_fire',
            'pathfinder_jakiro_ice_path_barrier',
            'pathfinder_jakiro_ice_path_repeat',
            'pathfinder_jakiro_ice_path_fast',
            'pathfinder_jakiro_ice_path_armour',
            'pathfinder_jakiro_liquid_fire_burst',
            'pathfinder_jakiro_liquid_fire_allies',
            'pathfinder_jakiro_liquid_fire_macropyre',
            'pathfinder_jakiro_macropyre_eternal',
            'pathfinder_jakiro_macropyre_burning_man',
            'pathfinder_jakiro_macropyre_heal',
            'pathfinder_jakiro_macropyre_cooldown_reduction']

    },
    {
        id: 'OgreMagi',
        name: 'Ogre-Magi',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/e/e0/Ogre_Magi_icon.png',
        desc: 'Aggron Stonebreak, the Ogre Magi, is a melee intelligence hero, famous for his random potential for extreme burst damage and his enormous health pool for an intelligence hero. He has good base attributes, and' +
            'some of the best attributes gain in the game, having a very high base strength, as well as the highest strength gain of any intelligence hero by far.',
        talents: [
            ['+240 Fireblast Damage', '25', '+60 Movement Speed'],
            ['+15% Bloodlust Movespeed', '20', '+30 Strength'],
            ['+275 Health', '15', '+80 Damage'],
            ['+75 Cast Range', '10', '+16 Ignite DPS'],
        ],
        abilities: ['fireblast', 'ignite', 'bloodlust', 'multicast', 'talentTree'],
        shards: ['pathfinder_special_om_aoe_fireblast',
            'pathfinder_special_ignite_fireblast',
            'pathfinder_special_friendly_ignite',
            'pathfinder_special_stunned_ignite',
            'pathfinder_special_om_giant_bloodlust',
            'pathfinder_special_om_multi_multicast',
            'pathfinder_special_om_aoe_multicast',
            'pathfinder_special_om_summoming']

    },
    {
        id: 'QueenofPain',
        name: 'Queen of Pain',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a1/Queen_of_Pain_icon.png',
        desc: 'Akasha, the Queen of Pain, is a ranged intelligence hero who uses her abilities to close in and deal huge area damage to the enemy. She is typically played in the middle lane as a ganker and semi-carry,' +
            'with her ability to appear in battle and deal damage in quick succession, as well as hunt down fleeing heroes with ease. ',
        talents: [
            ['+24% Critical Strike (200%)', '25', 'Scream of Pain 1.5s Stun'],
            ['+525 AoE Shadow Strike', '20', '+25% Spell Lifesteal'],
            ['+30 Attack Speed', '15', '10% Cooldown Reduction'],
            ['+9 Strength', '10', '+20 Damage'],
        ],
        abilities: ['shadowStrike', 'blink', 'screamOfPain', 'sonicWave', 'talentTree'],
        shards: ['aghsfort_special_queenofpain_shadow_strike_on_attack',
            'aghsfort_special_queenofpain_shadow_strike_chain',
            'aghsfort_special_queenofpain_shadow_strike_scream',
            'aghsfort_special_queenofpain_blink_generates_scream',
            'aghsfort_special_queenofpain_blink_attack_speed',
            'aghsfort_special_queenofpain_blink_shadow_strike',
            'aghsfort_special_queenofpain_scream_of_pain_resets_blink',
            'aghsfort_special_queenofpain_scream_of_pain_knockback',
            'aghsfort_special_queenofpain_scream_of_pain_restores_caster',
            'aghsfort_special_queenofpain_sonic_wave_trail',
            'aghsfort_special_queenofpain_sonic_wave_circle',
            'aghsfort_special_queenofpain_sonic_wave_attack_buff']
    },
    {
        id: 'Windranger',
        name: 'Windranger',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/6/60/Windranger_icon.png',
        desc: 'Lyralei, the Windranger, is a ranged intelligence hero that uses powerful abilities in conjunction with her physical attack to take down enemies. Despite being an intelligence Hero, Windranger\'s' +
            'playstyle resembles that of an agility Hero, due in large part to her skill set. ',
        talents: [
            ['25% Cooldown Reduction', '25', '+10s Focus Fire Duration'],
            ['+1s Shackleshot Target', '20', '+16% Spell Lifesteal'],
            ['+100 Attack Speed', '15', '+100 Powershot Damage'],
            ['+1s Shackleshot Stun Duration', '10', '+2.5 Mana Regen'],
        ],
        abilities: ['shackleshot', 'powershot', 'windrun', 'focusFire', 'talentTree'],
        shards: ['pathfinder_special_windranger_shackleshot_aoe',
            'pathfinder_special_windranger_windrun_cyclone',
            'pathfinder_special_windranger_shackleshot_armor',
            'pathfinder_special_windranger_shackleshot_sleep',
            'pathfinder_special_windranger_powershot_multishot',
            'pathfinder_special_windranger_powershot_repeating',
            'pathfinder_special_windranger_windrun_aoe',
            'pathfinder_special_windranger_focusfire_trueshot',
            'pathfinder_special_windranger_focusfire_global']
    },
    {
        id: 'WinterWyvern',
        name: 'Winter Wyvern',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/4/4a/Winter_Wyvern_icon.png',
        desc: 'Auroth, the Winter Wyvern, is a ranged intelligence hero whose arsenal of spells gives her powerful nuking capabilities. Usually played as a lane support, Winter Wyvern\'s spells allow her to fulfill a myriad of roles depending on what her team needs.',
        talents: [
            ['Splinter Blast 1.5s Stun', '25', '+1.5s Winter\'s Curse Duration'],
            ['+11% Spell Amplification', '20', '+12% Artic Burn Slow'],
            ['+30 Attack Speed', '15', '+275 Health'],
            ['+50 Damage', '10', '+1% Cold Embrace Heal'],
        ],
        abilities: ['arcticBurn', 'splinterBlast', 'coldEmbrace', 'wintersCurse', 'talentTree'],
        shards: ['aghsfort_special_winter_wyvern_arctic_burn_doubleattack',
            'aghsfort_special_winter_wyvern_arctic_burn_splash_damage',
            'aghsfort_special_winter_wyvern_arctic_burn_splitshot',
            'aghsfort_special_winter_wyvern_splinter_blast_vacuum',
            'aghsfort_special_winter_wyvern_splinter_blast_main_target_hit',
            'aghsfort_special_winter_wyvern_splinter_blast_heal',
            'aghsfort_special_winter_wyvern_cold_embrace_charges',
            'aghsfort_special_winter_wyvern_cold_embrace_blast_on_end',
            'aghsfort_special_winter_wyvern_cold_embrace_magic_damage_block',
            'aghsfort_special_winter_wyvern_winters_curse_transfer',
            'aghsfort_special_winter_wyvern_winters_curse_heal_on_death',
            'aghsfort_special_winter_wyvern_winters_curse_damage_amp']
    },
    {
        id: 'WitchDoctor',
        name: 'Witch Doctor',
        image: 'https://static.wikia.nocookie.net/dota2_gamepedia/images/3/33/Witch_Doctor_icon.png',
        desc: 'Zharvakko, the Witch Doctor, is a ranged intelligence hero who can take on the role of a support or a ganker. A master of voodoo curses and healing arts,' +
            'he possesses several positioning-dependent crowd control/damage spells as well as a heal that scales well into the late game.',
        talents: [
            ['+60s Death Ward Damage', '25', '+1.2% Max Health Voodoo Restoration'],
            ['+1 Maledict Tick', '20', '+100 Death Ward Attack Range'],
            ['+80 Maledict AoE', '15', '+2 Cask Bounces'],
            ['+5 Armor', '10', '+60 Damage'],
        ],
        abilities: ['paralyzingCask', 'voodooRestoration', 'maledict', 'deathWard', 'talentTree'],
        shards: ['aghsfort_special_witch_doctor_paralyzing_cask_multicask',
            'aghsfort_special_witch_doctor_paralyzing_cask_applies_maledict',
            'aghsfort_special_witch_doctor_paralyzing_cask_aoe_damage',
            'aghsfort_special_witch_doctor_paralyzing_cask_attack_procs',
            'aghsfort_special_witch_doctor_maledict_aoe_procs',
            'aghsfort_special_witch_doctor_maledict_death_restoration',
            'aghsfort_special_witch_doctor_maledict_affects_allies',
            'aghsfort_special_witch_doctor_maledict_infectious',
            'aghsfort_special_witch_doctor_voodoo_restoration_enemy_damage',
            'aghsfort_special_witch_doctor_voodoo_restoration_lifesteal',
            'aghsfort_special_witch_doctor_voodoo_restoration_damage_amp',
            'aghsfort_special_witch_doctor_voodoo_restoration_mana_restore',
            'aghsfort_special_witch_doctor_death_ward_no_channel',
            'aghsfort_special_witch_doctor_death_ward_damage_resist',
            'aghsfort_special_witch_doctor_death_ward_splitshot']
    }

]

export default Heroes