const Items = {
    nullTalisman: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/90/Null_Talisman_icon.png'), name: 'Null Talisman' },
    wraithBand: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/55/Wraith_Band_icon.png'), name: 'Wraith Band' },
    bracer: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6e/Bracer_icon.png'), name: 'Bracer' },
    soulRing: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a6/Soul_Ring_icon.png'), name: 'Soul Ring' },
    orbOfCorrosion: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/97/Orb_of_Corrosion_icon.png'), name: 'Orb of Corrosion' },
    falconBlade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/4/4a/Falcon_Blade_icon.png'), name: 'Falcon Blade' },
    powerTreads: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6b/Power_Treads_icon.png'), name: 'Power Treads' },
    oblivionStaff: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/7b/Oblivion_Staff_icon.png'), name: 'Oblivion Staff' },
    phaseBoots: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/98/Phase_Boots_icon.png'), name: 'Phase Boots' },
    perseverance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/fb/Perseverance_icon.png'), name: 'Perseverance' },
    maskOfMadness: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/76/Mask_of_Madness_icon.png'), name: 'Mask of Madness' },
    handOfMidas: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5b/Hand_of_Midas_icon.png'), name: 'Hand of Midas' },
    helmOfDominator: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/97/Helm_of_the_Dominator_icon.png'), name: 'Helm of Dominator' },
    bootsOfTravel: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6d/Boots_of_Travel_1_icon.png'), name: 'Boots of Travel' },
    moonShard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/21/Moon_Shard_icon.png'), name: 'Moon Shard' },
    buckler: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ae/Buckler_%28Inactive%29_icon.png'), name: 'Buckler' },
    headdress: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/0/03/Headdress_icon.png'), name: 'Headdress' },
    ringOfBasilius: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/26/Ring_of_Basilius_%28Active%29_icon.png'), name: 'Ring of Basilius' },
    urnOfShadows: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/58/Urn_of_Shadows_icon.png'), name: 'Urn of Shadows' },
    tranquilBoots: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/23/Tranquil_Boots_%28Active%29_icon.png'), name: 'Tranquil Boots' },
    medallionOfCourage: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d9/Medallion_of_Courage_icon.png'), name: 'Medallion of Courage' },
    arcaneBoots: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/be/Arcane_Boots_icon.png'), name: 'Arcane Boots' },
    drumOfEndurance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/91/Drum_of_Endurance_icon.png'), name: 'Drum of Endurance' },
    mekansm: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f7/Mekansm_icon.png'), name: 'Mekansm' },
    holyLocket: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/4/48/Holy_Locket_icon.png'), name: 'Holy Locket' },
    vladimirsOffering: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/28/Vladmir%27s_Offering_icon.png'), name: 'Vladimir\'s Offering' },
    spiritVessel: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/2a/Spirit_Vessel_icon.png'), name: 'Spirit Vessel' },
    pipeOfInsight: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/76/Pipe_of_Insight_icon.png'), name: 'Pipe of Insight' },
    guardianGreaves: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/94/Guardian_Greaves_icon.png'), name: 'Guardian Greaves' },
    veilOfDiscord: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f2/Veil_of_Discord_icon.png'), name: 'Veil of Discord' },
    glimmerCape: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/ce/Glimmer_Cape_icon.png'), name: 'Glimmer Cape' },
    necronomicon: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/30/Necronomicon_1_icon.png'), name: 'Necronomicon' },
    forceStaff: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a2/Force_Staff_icon.png'), name: 'Force Staff' },
    aetherLens: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d4/Aether_Lens_icon.png'), name: 'Aether Lens' },
    witchBlade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/68/Witch_Blade_icon.png'), name: 'Witch Blade' },
    euls: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/80/Eul%27s_Scepter_of_Divinity_icon.png'), name: 'Eul\'s Scepter of Divinity' },
    dagon: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Dagon_1_icon.png'), name: 'Dagon' },
    rodOfAtos: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/66/Rod_of_Atos_icon.png'), name: 'Rod of Atos' },
    orchidMalevolence: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ad/Orchid_Malevolence_icon.png'), name: 'Orchid Malevolence' },
    solarCrest: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/36/Solar_Crest_icon.png'), name: 'Solar Crest' },
    refresherOrb: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/e/e2/Refresher_Orb_icon.png'), name: 'Refresher Orb' },
    octarineCore: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/13/Octarine_Core_icon.png'), name: 'Octarine Orb' },
    scytheOfVyse: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/54/Scythe_of_Vyse_icon.png'), name: 'Scythe of Vyse' },
    gleipnir: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5d/Gleipnir_icon.png'), name: 'Gleipnir' },
    windWaker: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/90/Wind_Waker_icon.png'), name: 'Windwaker' },
    hoodOfDefiance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ad/Hood_of_Defiance_icon.png'), name: 'Hood of Defiance' },
    vanguard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ab/Vanguard_icon.png'), name: 'Vanguard' },
    bladeMail: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/18/Blade_Mail_icon.png'), name: 'Blade mail' },
    aeonDisk: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/2b/Aeon_Disk_icon.png'), name: 'Aeon Disk' },
    soulBooster: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/2f/Soul_Booster_icon.png'), name: 'Soul Booster' },
    eternalShroud: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c5/Eternal_Shroud_icon.png'), name: 'Eternal Shroud' },
    crimsonGuard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/70/Crimson_Guard_icon.png'), name: 'Crimson Guard' },
    lotusOrb: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c8/Lotus_Orb_icon.png'), name: 'Lotus Orb' },
    bkb: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/72/Black_King_Bar_icon.png'), name: 'Black King Bar' },
    hurricanePike: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/13/Hurricane_Pike_icon.png'), name: 'Hurricane Pike' },
    linkensSphere: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/23/Linken%27s_Sphere_icon.png'), name: 'Linkens Sphere' },
    mantaStyle: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/84/Manta_Style_icon.png'), name: 'Manta Style' },
    heart: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/75/Heart_of_Tarrasque_icon.png'), name: 'Heart of Tarrasque' },
    shivasGuard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/b6/Shiva%27s_Guard_icon.png'), name: 'Shiva\'s Guard' },
    assaultCuirass: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d3/Assault_Cuirass_icon.png'), name: 'Assault Cuirass' },
    bloodstone: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5a/Bloodstone_icon.png'), name: 'Bloodstone' },
    crystalys: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/3f/Crystalys_icon.png'), name: 'Crystalys' },
    meteorHammer: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/54/Meteor_Hammer_icon.png'), name: 'Meteor Hammer' },
    armlet: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/8d/Armlet_of_Mordiggian_%28Inactive%29_icon.png'), name: 'Armlet of Mordiggian' },
    skullBasher: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/9d/Skull_Basher_icon.png'), name: 'Skull Basher' },
    shadowBlade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/0/0f/Shadow_Blade_icon.png'), name: 'Shadow Blade' },
    desolator: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/84/Desolator_icon.png'), name: 'Desolator' },
    battleFury: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c1/Battle_Fury_icon.png'), name: 'Battle Fury' },
    eBlade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5b/Ethereal_Blade_icon.png'), name: 'Ethereal Blade' },
    nullifier: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Nullifier_icon.png'), name: 'Nullifier' },
    mkb: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/b0/Monkey_King_Bar_icon.png'), name: 'Monkey King Bar' },
    daedalus: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/24/Daedalus_icon.png'), name: 'Daedalus' },
    radiance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/df/Radiance_%28Active%29_icon.png'), name: 'Radiance' },
    butterfly: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/28/Butterfly_icon.png'), name: 'Butterfly' },
    silverEdge: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/91/Silver_Edge_icon.png'), name: 'Silver Edge' },
    bloodthorn: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f4/Bloodthorn_icon.png'), name: 'Bloodthorn' },
    abyssalBlade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/3b/Abyssal_Blade_icon.png'), name: 'Abyssal Blade' },
    dragonLance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/db/Dragon_Lance_icon.png'), name: 'Dragon Lance' },
    echoSabre: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6b/Echo_Sabre_icon.png'), name: 'Echo Sabre' },
    maelstrom: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/65/Maelstrom_icon.png'), name: 'Maelstrom' },
    kaya: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/65/Kaya_icon.png'), name: 'Kaya' },
    sange: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/fc/Sange_icon.png'), name: 'Sange' },
    yasha: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d1/Yasha_icon.png'), name: 'Yasha' },
    diffusalBlade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/65/Diffusal_Blade_1_icon.png'), name: 'Diffusal Blade' },
    mageSlayer: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/18/Mage_Slayer_icon.png'), name: 'Mage Slayer' },
    heavensHalberd: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c6/Heaven%27s_Halberd_icon.png'), name: 'Heaven\'s Halberd' },
    kayaSange: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/67/Kaya_and_Sange_icon.png'), name: 'Kaya & Sange' },
    sangeYasha: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/b4/Sange_and_Yasha_icon.png'), name: 'Sange & Yasha' },
    yashaKaya: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/19/Yasha_and_Kaya_icon.png'), name: 'Yasha & Kaya' },
    satanic: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/dd/Satanic_icon.png'), name: 'Satanic' },
    eyeOfSkadi: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/1e/Eye_of_Skadi_icon.png'), name: 'Eye of Skadi' },
    mjollnir: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/9d/Mjollnir_icon.png'), name: 'Mjollnir' },
    arcaneBlink: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/28/Arcane_Blink_icon.png'), name: 'Arcane Blink' },
    overwhelmingBlink: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6d/Overwhelming_Blink_icon.png'), name: 'Overwhelming Blink' },
    swiftBlink: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/4/47/Swift_Blink_icon.png'), name: 'Swift Blink' },
    bootsOfSpeed: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/97/Boots_of_Speed_icon.png'), name: 'Boots of Speed' }
}
// 60x44
export default Items