const Items = {
    item_null_talisman: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/90/Null_Talisman_icon.png'), name: 'Null Talisman' },
    item_wraith_band: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/55/Wraith_Band_icon.png'), name: 'Wraith Band' },
    item_bracer: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6e/Bracer_icon.png'), name: 'Bracer' },
    item_soul_ring: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a6/Soul_Ring_icon.png'), name: 'Soul Ring' },
    item_orb_of_corrosion: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/97/Orb_of_Corrosion_icon.png'), name: 'Orb of Corrosion' },
    item_falcon_blade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/4/4a/Falcon_Blade_icon.png'), name: 'Falcon Blade' },
    item_power_treads: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6b/Power_Treads_icon.png'), name: 'Power Treads' },
    item_oblivion_staff: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/7b/Oblivion_Staff_icon.png'), name: 'Oblivion Staff' },
    item_phase_boots: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/98/Phase_Boots_icon.png'), name: 'Phase Boots' },
    item_pers: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/fb/Perseverance_icon.png'), name: 'Perseverance' },
    item_mask_of_madness: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/76/Mask_of_Madness_icon.png'), name: 'Mask of Madness' },
    item_hand_of_midas: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5b/Hand_of_Midas_icon.png'), name: 'Hand of Midas' },
    item_feet_of_midas: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5b/Hand_of_Midas_icon.png'), name: 'Hand of Midas' },
    item_helm_of_the_dominator: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/97/Helm_of_the_Dominator_icon.png'), name: 'Helm of Dominator' },
    item_travel_boots_1: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6d/Boots_of_Travel_1_icon.png'), name: 'Boots of Travel' },
    item_travel_boots_2: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6d/Boots_of_Travel_1_icon.png'), name: 'Boots of Travel' },
    item_moon_shard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/21/Moon_Shard_icon.png'), name: 'Moon Shard' },
    item_buckler: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ae/Buckler_%28Inactive%29_icon.png'), name: 'Buckler' },
    item_headdress: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/0/03/Headdress_icon.png'), name: 'Headdress' },
    item_ring_of_basilius: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/26/Ring_of_Basilius_%28Active%29_icon.png'), name: 'Ring of Basilius' },
    item_urn_of_shadows: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/58/Urn_of_Shadows_icon.png'), name: 'Urn of Shadows' },
    item_tranquil_boots: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/23/Tranquil_Boots_%28Active%29_icon.png'), name: 'Tranquil Boots' },
    item_medallion_of_courage: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d9/Medallion_of_Courage_icon.png'), name: 'Medallion of Courage' },
    item_arcane_boots: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/be/Arcane_Boots_icon.png'), name: 'Arcane Boots' },
    item_ancient_janggo: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/91/Drum_of_Endurance_icon.png'), name: 'Drum of Endurance' },
    item_mekansm: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f7/Mekansm_icon.png'), name: 'Mekansm' },
    item_holy_locket: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/4/48/Holy_Locket_icon.png'), name: 'Holy Locket' },
    item_vladmir: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/28/Vladmir%27s_Offering_icon.png'), name: 'Vladimir\'s Offering' },
    item_spirit_vessel: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/2a/Spirit_Vessel_icon.png'), name: 'Spirit Vessel' },
    item_pipe: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/76/Pipe_of_Insight_icon.png'), name: 'Pipe of Insight' },
    item_guardian_greaves: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/94/Guardian_Greaves_icon.png'), name: 'Guardian Greaves' },
    item_veil_of_discord: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f2/Veil_of_Discord_icon.png'), name: 'Veil of Discord' },
    item_glimmer_cape: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/ce/Glimmer_Cape_icon.png'), name: 'Glimmer Cape' },
    item_necronomicon_1: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/30/Necronomicon_1_icon.png'), name: 'Necronomicon' },
    item_necronomicon_2: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/30/Necronomicon_1_icon.png'), name: 'Necronomicon' },
    item_necronomicon_3: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/30/Necronomicon_1_icon.png'), name: 'Necronomicon' },
    item_force_staff: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a2/Force_Staff_icon.png'), name: 'Force Staff' },
    item_aether_lens: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d4/Aether_Lens_icon.png'), name: 'Aether Lens' },
    item_witch_blade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/68/Witch_Blade_icon.png'), name: 'Witch Blade' },
    item_cyclone: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/80/Eul%27s_Scepter_of_Divinity_icon.png'), name: 'Eul\'s Scepter of Divinity' },
    item_dagon_1: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Dagon_1_icon.png'), name: 'Dagon' },
    item_dagon_2: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Dagon_1_icon.png'), name: 'Dagon' },
    item_dagon_3: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Dagon_1_icon.png'), name: 'Dagon' },
    item_dagon_4: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Dagon_1_icon.png'), name: 'Dagon' },
    item_dagon_5: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Dagon_1_icon.png'), name: 'Dagon' },
    item_rod_of_atos: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/66/Rod_of_Atos_icon.png'), name: 'Rod of Atos' },
    item_orchid: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ad/Orchid_Malevolence_icon.png'), name: 'Orchid Malevolence' },
    item_solar_crest: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/36/Solar_Crest_icon.png'), name: 'Solar Crest' },
    item_refresher: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/e/e2/Refresher_Orb_icon.png'), name: 'Refresher Orb' },
    item_octarine_core: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/13/Octarine_Core_icon.png'), name: 'Octarine Orb' },
    item_sheepstick: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/54/Scythe_of_Vyse_icon.png'), name: 'Scythe of Vyse' },
    item_gleipnir: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5d/Gleipnir_icon.png'), name: 'Gleipnir' },
    item_windwaker: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/90/Wind_Waker_icon.png'), name: 'Windwaker' },
    item_hood_of_defiance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ad/Hood_of_Defiance_icon.png'), name: 'Hood of Defiance' },
    item_vanguard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/a/ab/Vanguard_icon.png'), name: 'Vanguard' },
    item_blade_mail: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/18/Blade_Mail_icon.png'), name: 'Blade mail' },
    item_aeon_disk: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/2b/Aeon_Disk_icon.png'), name: 'Aeon Disk' },
    item_soul_booster: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/2f/Soul_Booster_icon.png'), name: 'Soul Booster' },
    item_eternal_shroud: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c5/Eternal_Shroud_icon.png'), name: 'Eternal Shroud' },
    item_crimson_guard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/70/Crimson_Guard_icon.png'), name: 'Crimson Guard' },
    item_lotus_orb: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c8/Lotus_Orb_icon.png'), name: 'Lotus Orb' },
    item_black_king_bar: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/72/Black_King_Bar_icon.png'), name: 'Black King Bar' },
    item_hurricane_pike: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/13/Hurricane_Pike_icon.png'), name: 'Hurricane Pike' },
    item_sphere: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/23/Linken%27s_Sphere_icon.png'), name: 'Linkens Sphere' },
    item_manta: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/84/Manta_Style_icon.png'), name: 'Manta Style' },
    item_heart: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/7/75/Heart_of_Tarrasque_icon.png'), name: 'Heart of Tarrasque' },
    item_shivas_guard: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/b6/Shiva%27s_Guard_icon.png'), name: 'Shiva\'s Guard' },
    item_assault: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d3/Assault_Cuirass_icon.png'), name: 'Assault Cuirass' },
    item_bloodstone: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5a/Bloodstone_icon.png'), name: 'Bloodstone' },
    item_lesser_crit: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/3f/Crystalys_icon.png'), name: 'Crystalys' },
    item_meteor_hammer: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/54/Meteor_Hammer_icon.png'), name: 'Meteor Hammer' },
    item_armlet: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/8d/Armlet_of_Mordiggian_%28Inactive%29_icon.png'), name: 'Armlet of Mordiggian' },
    item_basher: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/9d/Skull_Basher_icon.png'), name: 'Skull Basher' },
    item_invis_sword: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/0/0f/Shadow_Blade_icon.png'), name: 'Shadow Blade' },
    item_desolator: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/8/84/Desolator_icon.png'), name: 'Desolator' },
    item_bfury: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c1/Battle_Fury_icon.png'), name: 'Battle Fury' },
    item_ethereal_blade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/5/5b/Ethereal_Blade_icon.png'), name: 'Ethereal Blade' },
    item_nullifier: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/bc/Nullifier_icon.png'), name: 'Nullifier' },
    item_monkey_king_bar: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/b0/Monkey_King_Bar_icon.png'), name: 'Monkey King Bar' },
    item_greater_crit: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/24/Daedalus_icon.png'), name: 'Daedalus' },
    item_radiance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/df/Radiance_%28Active%29_icon.png'), name: 'Radiance' },
    item_butterfly: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/28/Butterfly_icon.png'), name: 'Butterfly' },
    item_silver_edge: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/91/Silver_Edge_icon.png'), name: 'Silver Edge' },
    item_bloodthorn: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f4/Bloodthorn_icon.png'), name: 'Bloodthorn' },
    item_abyssal_blade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/3/3b/Abyssal_Blade_icon.png'), name: 'Abyssal Blade' },
    item_dragon_lance: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/db/Dragon_Lance_icon.png'), name: 'Dragon Lance' },
    item_echo_sabre: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6b/Echo_Sabre_icon.png'), name: 'Echo Sabre' },
    item_maelstrom: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/65/Maelstrom_icon.png'), name: 'Maelstrom' },
    item_kaya: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/65/Kaya_icon.png'), name: 'Kaya' },
    item_sange: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/f/fc/Sange_icon.png'), name: 'Sange' },
    item_yasha: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d1/Yasha_icon.png'), name: 'Yasha' },
    item_diffusal_blade: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/65/Diffusal_Blade_1_icon.png'), name: 'Diffusal Blade' },
    item_mage_slayer: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/18/Mage_Slayer_icon.png'), name: 'Mage Slayer' },
    item_heavens_halberd: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c6/Heaven%27s_Halberd_icon.png'), name: 'Heaven\'s Halberd' },
    item_kaya_and_sange: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/67/Kaya_and_Sange_icon.png'), name: 'Kaya & Sange' },
    item_sange_and_yasha: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/b/b4/Sange_and_Yasha_icon.png'), name: 'Sange & Yasha' },
    item_yasha_and_kaya: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/19/Yasha_and_Kaya_icon.png'), name: 'Yasha & Kaya' },
    item_satanic: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/d/dd/Satanic_icon.png'), name: 'Satanic' },
    item_skadi: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/1/1e/Eye_of_Skadi_icon.png'), name: 'Eye of Skadi' },
    item_mjollnir: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/9d/Mjollnir_icon.png'), name: 'Mjollnir' },
    item_arcane_blink: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/2/28/Arcane_Blink_icon.png'), name: 'Arcane Blink' },
    item_overwhelming_blink: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6d/Overwhelming_Blink_icon.png'), name: 'Overwhelming Blink' },
    item_swift_blink: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/4/47/Swift_Blink_icon.png'), name: 'Swift Blink' },
    item_blink: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/4/4c/Blink_Dagger_icon.png/revision/latest/scale-to-width-down/100?cb=20160530164152'), name: 'Blink Dagger' },
    item_boots: { link: ('https://static.wikia.nocookie.net/dota2_gamepedia/images/9/97/Boots_of_Speed_icon.png'), name: 'Boots of Speed' }
}
// 60x44
export default Items